name: Terraform CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      # 🔥 NEW STEP: Install conftest
      - name: Install conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.43.0/conftest_0.43.0_Linux_x86_64.tar.gz | tar xz
          sudo mv conftest /usr/local/bin/

      # 🔥 NEW STEP: Run Policy Check
      - name: Policy Check (OPA)
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json
          conftest test tfplan.json --policy policy/
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      - name: Terraform Apply (Main)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
